name: Selenium Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  selenium-tests:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Give permission to Gradle
        run: chmod +x gradlew

      - name: Run Selenium Tests
        run: ./gradlew test

      - name: Upload screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: build/screenshots

      - name: Upload Test Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: selenium-test-report
          path: build/reports/tests/test